name: v_chat_sdk_sample
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.0.4
  shared_preferences: ^2.0.15
  flutter_facebook_auth: ^5.0.6
  supabase_flutter: ^1.2.2
  http: ^0.13.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  bottom_navy_bar: ^6.0.0
  textless: ^6.6.6
  url_launcher: ^6.1.6
  file_picker: ^5.2.2
  firebase_messaging: ^14.1.3
  custom_navigation_bar: ^0.8.2
  introduction_screen: ^3.1.1
  flex_color_scheme: ^6.1.1
  get: 4.6.5
  flutter_platform_alert: ^0.3.0
  flutter: 
    sdk: flutter
  v_chat_sdk_core: ^0.0.2
  v_chat_utils: ^0.0.3
  v_chat_message_page: ^0.0.1
  v_chat_firebase_fcm: ^0.0.1
  v_chat_room_page: ^0.0.1
  animated_login: ^1.5.5
  mime: ^1.0.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  fluttertoast: ^8.1.1
  mime_type: ^1.0.0
  file_sizes: ^1.0.6
  path: ^1.8.2
  encrypt: ^5.0.1
  image_cropper: ^3.0.1
  wechat_camera_picker: ^3.6.3
  http_parser: ^4.0.2
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: ic_launcher
  image_path: assets/images/logo.png
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
flutter_intl:
  enabled: false
