name: v_chat_sdk_sample
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  flutterfire_ui: ^0.4.3+20
  get: 4.6.5
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.3
  flutter: 
    sdk: flutter
  v_chat_sdk_core: 
    path: ../../packages/v_chat_sdk_core

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

