name: v_chat_firebase_fcm
description: v chat fcm implementations
version: 0.2.1
homepage: https://hatemragab.github.io/VChatSdk-Documentation/
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk/v_chat_firebase_fcm

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  v_chat_utils: ^0.2.1
  v_chat_sdk_core: ^0.2.1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  eraser: ^2.0.1
  flutter_app_badger: ^1.5.0
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.1

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
