name: v_chat_sdk_core
description: core package for v chat sdk witch use socket.io with node js and mongodb db
version: 0.4.3+2
homepage: https://hatemragab.github.io/VChatSdk-Documentation/
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk/tree/v2/core_packages/v_chat_sdk_core

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  v_chat_utils: ^0.4.3
  http: ^0.13.5
  logging: ^1.1.1
  chopper: ^6.0.0
  http_parser: ^4.0.2
  encrypt: ^5.0.1
  crypto: ^3.0.2
  socket_io_client: ^2.0.1
  latlong2: ^0.8.1
  path: ^1.8.2
  sqflite: ^2.2.4+1
#  stack_trace: ^1.11.0
  html: ^0.15.1
  cross_file: ^0.3.3+2
  objectid: ^2.1.0
  sqlite3_flutter_libs: ^0.5.12
  diacritic: ^0.1.3
  #for testing only
  random_string: ^2.3.1
  meta: ^1.8.0

  flutter_fgbg: ^0.2.2
  flutter_cache_manager: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  lints: ^2.0.1
  flutter_lints: ^2.0.1

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
