name: v_chat_sdk
description: official sdk for vchat to impement chat system into new or exist flutter app
version: 0.0.7
homepage: https://github.com/hatemragab/v_chat_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"



dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  textless: ^6.6.6
  get: ^4.3.8
  get_storage: ^2.0.3
  dio: ^4.0.1
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  image_picker: ^0.8.4+3
  sqflite: ^2.0.0+4
  path_provider: ^2.0.5
  socket_io_client: ^1.0.1
  intl: ^0.17.0
  file_picker: ^4.1.6
  flutter_native_image: ^0.0.6+1
  permission_handler: ^8.2.5
  flutter_video_info: ^1.2.0
  video_thumbnail: ^0.4.3
  video_player: ^2.2.5
  record: ^3.0.0
  stop_watch_timer: ^1.3.1
  audioplayers: ^0.20.1
  open_file: ^3.2.1
  photo_view: ^0.13.0
  chewie: ^1.2.2
  cached_network_image: ^3.1.0
  timeago: ^3.1.0
  flutter_local_notifications: ^9.0.0
  bot_toast: ^4.0.1
  google_fonts: ^2.1.0
  path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
