name: v_chat_sdk
description: official sdk for v chat this is a complete chat ecosystem use flutter for clint node js and socket io for server side flutter chat v chat sdk
version: 1.1.1
homepage: https://github.com/hatemragab/v_chat_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # state management
  bloc: ^8.0.2
  # state management
  flutter_bloc: ^8.0.1

  # upload files
  http: ^0.13.4

  # speed up the text theme access
  textless: ^6.6.6
  # http request
  dio: ^4.0.4
  #init firebase
  firebase_core: ^1.11.0
  # for integrate notification with firebase
  firebase_messaging: ^11.2.5
  image_picker: ^0.8.4+4
  # store chat offline /no web support
  sqflite: ^2.0.2
  # sql data base path /no web support
  path_provider: ^2.0.8
  # real time chat
  socket_io_client: ^1.0.2
  # date format
  intl: ^0.17.0
  # get files
  file_picker: ^4.3.1
  # crop image and reduce its quality /no web support
  flutter_native_image: ^0.0.6+1
  # ask for files permissions /no web support
  permission_handler: ^8.3.0
  # get video info /no web support
  flutter_video_info: ^1.2.0
  # video_thumbnail /no web support
  video_thumbnail: ^0.4.3
  # flutter official video_player
  video_player: ^2.2.11
  # record voice chat
  record: ^3.0.2
  # voice recording timer
  stop_watch_timer: ^1.3.1
  # play voice note
  audioplayers: ^0.20.1
  # open chat file directed to its app /no web support
  open_file: ^3.2.1
  #show chat photo
  photo_view: ^0.13.0
  # show chat video /no web support
  video_viewer: ^1.2.7
  # cached_network_image /no web support
  cached_network_image: ^3.2.0
  # message time
  timeago: ^3.1.0
  #in app notifications /no web support
  flutter_local_notifications: ^9.2.0
  path: ^1.8.0
  # save user access token
  flutter_secure_storage: ^5.0.2
  # success alert
  fluttertoast: ^8.0.8
  # for inject dependency
  get_it: ^7.2.0
  meta: ^1.7.0
  # for has the password
  crypto: ^3.0.1
  # for save user app language
  shared_preferences: ^2.0.12




dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist