name: core_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  v_chat_sdk_core:
    path: ../../packages/v_chat_sdk_core
  textless:
#  v_chat_firebase_fcm:
#    path: ../../packages/v_chat_firebase_fcm
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

