name: v_chat_message_page
description: v chat sdk message page ui
version: 0.0.1
homepage: https://hatemragab.github.io/VChatSdk-Documentation/
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  v_chat_utils: ^0.0.6
  v_chat_sdk_core: ^0.0.3
  v_chat_voice_player: ^0.0.4
  v_chat_input_ui: ^0.0.5
  v_chat_media_editor: ^0.0.4
  map_launcher: ^2.4.0
  swipe_to: ^1.0.2
  share_plus: ^6.3.0
  scroll_to_index: ^3.0.1
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
#  assets:
#    - assets/
#    - assets/data/

