name: media_editor_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  v_chat_media_editor:
    path: ../../ui_packages/v_chat_media_editor
  v_chat_sdk_core:
    path: ../../packages/v_chat_sdk_core

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

