name: v_chat_utils
description: utils for v chat sdk
version: 0.0.2
homepage: https://hatemragab.github.io/VChatSdk-Documentation/
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mime_type: ^1.0.0
  build_context: ^3.0.0
  adaptive_dialog: ^1.8.0+1
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  textless: ^6.6.6
  file_picker: ^5.2.3
  image_cropping: ^0.0.13
  image: ^3.2.2
  image_cropper: ^3.0.0
  wechat_camera_picker: ^3.6.5
  encrypt: ^5.0.1
  shared_preferences: ^2.0.15
  progress_dialog_null_safe: ^1.0.7
  latlong2: ^0.8.1
  file_sizes: ^1.0.6
  path: ^1.8.2
  cross_file: ^0.3.3+2
  mime: ^1.0.2
  http: ^0.13.5
  collection: ^1.16.0
  http_parser: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
